---
version: 2
jobs:
  node-latest: &test
  build:
    docker:
      - image: node:latest
    working_directory: ~/cli
    steps:
      - checkout
      - restore_cache: &restore_cache
          keys:
            - v1-npm-{{checksum ".circleci/config.yml"}}-{{ checksum "yarn.lock"}}
            - v1-npm-{{checksum ".circleci/config.yml"}}
      - run:
          name: Install dependencies
          command: .circleci/greenkeeper
      - run: ./bin/run --help
      - run:
          name: Installing Heroku CLI
          command: curl https://cli-assets.heroku.com/install.sh | sh
      - run:
          name: Setting up plugin
          command: yarn global add oclif && heroku plugins:link
      - run:
          name: Setting up manifest
          command: heroku addons:admin:manifest:generate -t
      - run:
          name: Testing
          command: yarn test
      - save_cache:
          key: v1-yarn-{{checksum ".circleci/config.yml"}}-{{checksum "yarn.lock"}}
          paths:
            - ~/cli/node_modules
            - /usr/local/share/.cache/yarn
            - /usr/local/share/.config/yarn
  node-8:
    <<: *test
    docker:
      - image: node:8

workflows:
  version: 2
  "@heroku-cli/addons-admin":
    jobs:
      - node-latest
      - node-8
