# ---
# version: 2
# jobs:
#   node-latest: &test
#     docker:
#       - image: node:14
#     working_directory: ~/cli
#     steps:
#       - checkout
#       - restore_cache: &restore_cache
#           keys:
#             - v1-npm-{{checksum ".circleci/config.yml"}}-{{ checksum "yarn.lock"}}
#             - v1-npm-{{checksum ".circleci/config.yml"}}
#       - run:
#           name: Install dependencies
#           command: .circleci/greenkeeper
#       - run: ./bin/run --help
#       - run:
#           name: Installing Heroku CLI
#           command: curl https://cli-assets.heroku.com/install.sh | sh
#       - run:
#           name: Setting up plugin and manifet
#           command: yarn global add oclif && heroku plugins:link
#       - run:
#           name: Testing
#           command: yarn test
#       - run:
#           name: Running nyc code coverage
#           command: ./node_modules/.bin/nyc report --reporter text-lcov > coverage.lcov
#       - save_cache:
#           key: v1-yarn-{{checksum ".circleci/config.yml"}}-{{checksum "yarn.lock"}}
#           paths:
#             - ~/cli/node_modules
#             - /usr/local/share/.cache/yarn
#             - /usr/local/share/.config/yarn
#   node-12:
#     <<: *test
#     docker:
#       - image: node:12

# workflows:
#   version: 2
#   "@heroku-cli/addons-admin":
#     jobs:
#       - node-latest
#       - node-12
