name: Node CI Suite

on:
  push

jobs:
  test:

    runs-on: ${{ matrix.os }}
    name: Node Tests

    strategy:
      matrix:
        node-version: [ 20.x, 22.x ]
        os: [ ubuntu-24.04, pub-hk-ubuntu-24.04-arm-small ]

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install -g yarn
      - run: yarn --frozen-lockfile --ignore-engines
      - name: unit tests
        run: yarn test
      - name: linting
        run: yarn lint
