name: Node CI Suite

on:
  push

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 14
        uses: actions/setup-node@v3
        with:
          node-version: 14
      - name: Installing Heroku CLI
        run: curl https://cli-assets.heroku.com/install.sh | sh
      - name: Setting up plugin and manifet
        run: yarn global add oclif && heroku plugins:link
      - run: yarn --frozen-lockfile
      - name: Testing
        run: yarn test
      - name: Running nyc code coverage
        run: ./node_modules/.bin/nyc report --reporter text-lcov > coverage.lcov
